### ISSUE TITLE
linux 环境下部署

### ISSUE THREAD

**Issue by mingyangzhu** [sdcb/PaddleSharp#1]
您好，请问可以部署到linux环境下嘛？我看有windows下的runtime，我的理解当前的程序包目前只能运行再windows x64环境下。请问是这样嘛？谢谢。

**Comment by sdcb** [comment]
是的，我特意做成了本地部署包与绑定包分离的设计，理论上在linux下应该没有问题（而且百度官方也提供了），只要弄一个linux的本地包即可，但我不方便在linux下做测试，需要更多的热心社区人员来帮忙 :) 。

**Comment by sdcb** [comment]
Closed as `PaddleSharp` now already support linux: https://github.com/sdcb/PaddleSharp
