### ISSUE TITLE
Win Server 2022 ”Sdcb.PaddleInference.PaddleConfig” Error

### ISSUE THREAD

**Issue by towerbit** [sdcb/PaddleSharp#10]
System.TypeInitializationException: “Sdcb.PaddleInference.PaddleConfig”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“dll\x64\paddle_inference_c.dll”: 动态链接库(DLL)初始化例程失败。 (异常来自 HRESULT:0x8007045A)。
   在 Sdcb.PaddleInference.Native.PaddleNative.PD_GetVersion()
   在 Sdcb.PaddleInference.PaddleConfig.AutoLoad()
   在 Sdcb.PaddleInference.PaddleConfig..cctor()

通过 Dependency Worker 检查 paddle_inference_c.dll 未报告缺失依赖库
已安装 VC++ Runtime Library 2015-2022
Win10 LTSC 2021 环境下运行正常

**Comment by sdcb** [comment]
![JDZL14NYRS T1XNAXY)CR%F](https://user-images.githubusercontent.com/1317141/167971248-8d0c95a1-f098-4066-b6a5-02c607898b34.jpg)
![}34M_%2%G(2PBJBDWVY{1SN](https://user-images.githubusercontent.com/1317141/167971258-a4d5cd70-4e73-4978-8ef5-5dffb4049681.jpg)
确认一下会不会和这个原因有关？

**Comment by towerbit** [comment]
1. 确认了 媒体基础和桌面体验已安装，Windows Media Player 运行正常
2. 设置了 PaddleConfig.Default.Usemkldnn = false
问题依旧，x64 noavx openblas dll 没找到，请问可否提供一个下载链接？

**Comment by sdcb** [comment]
我有两台Windows Server 2022，都没有问题……
x64 noavx是在群共享文件。
