### ISSUE TITLE
Downloads for English V3 and English V4 Stalling

### ISSUE THREAD

**Issue by TheWorldEndsWithUs** [sdcb/PaddleSharp#105]
### Describe the bug

Whenever I run the default code found from the [online docs example](https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md) on my Windows 11 64 bit machine the download stalls. It hangs forever. 

### Steps to reproduce the bug

`        private async Task<Rectangle[]> runPaddleOCR(Mat src)
        {
            List<Rectangle> ocrResults = new List<Rectangle>();
            FullOcrModel model = await OnlineFullModels.EnglishV4.DownloadAsync();
            using (PaddleOcrAll all = new PaddleOcrAll(model, PaddleDevice.Mkldnn())
            {
                AllowRotateDetection = true, 
                Enable180Classification = false, 
            })
            {
                PaddleOcrResult result = all.Run(src);
                Console.WriteLine("Detected all texts: \n" + result.Text);
                foreach (PaddleOcrResultRegion region in result.Regions)
                {
                    var boundingRect = region.Rect.BoundingRect();
                    Rectangle rect = new Rectangle(boundingRect.X, boundingRect.Y, boundingRect.Width, boundingRect.Height);
                    ocrResults.Add(rect);
                    Console.WriteLine($"Text: {region.Text}, Score: {region.Score}, RectCenter: {region.Rect.Center}, RectSize:    {region.Rect.Size}, Angle: {region.Rect.Angle}");
                }
            }

            return ocrResults.ToArray();

        }`

My code is above it always hangs on the downloadAsync line never reaching the using statement. I've tried EnglishV3 and EnglishV4. 

### Expected behavior

I'd like the file to download and run the model.

### IDE

Visual Studio 2022 Community

### OS version

Windows 11 64 bit

**Comment by n0099** [comment]
#104 #84 #80 #62 #32

**Comment by TheWorldEndsWithUs** [comment]
Hey! Thank you for getting back to me! I downloaded the models and put them in the AppData folder as instructed, however the download still stalls for some reason. Thank you for your response, but I might use Tesseract for the time being so no rush to figure it out.

**Comment by n0099** [comment]
Did you uncompressed that `.tar`?

**Comment by TheWorldEndsWithUs** [comment]
Yes the file is unzipped and in the correct folder. I don't mind using the GlobalModelDirectory as the folder for now. The application refuses to load the model for some reason.
![image](https://github.com/user-attachments/assets/0292ff8b-42aa-477e-b394-a440830a23a2)

**Comment by n0099** [comment]
Please remove the suffix `_infer` from the unextracted folder name following https://github.com/sdcb/PaddleSharp/blob/475ed956cf4da1b4bbfb09c6f0b8246e6703f6fb/src/Sdcb.PaddleOCR.Models.LocalV4/KnownModels.cs#L16-L28

**Comment by TheWorldEndsWithUs** [comment]
This worked! I got rid of the Online Model library and downloaded the Local model library. Now the local example works perfectly. Thank you!
