### ISSUE TITLE
Linux: Unable to load shared library 'paddle_inference_c'

### ISSUE THREAD

**Issue by hodachuy** [sdcb/PaddleSharp#109]
### Describe the bug

Connection type: Window Subsystem for Linux (WSL)
Connection target: Ubuntu-22.04

System.DllNotFoundException: 'Unable to load shared library 'paddle_inference_c', dependencies load status:
libgomp.so.1: OK, handle=55609a9c0480
libiomp5.so: OK, handle=55609a9c2aa0
libdnnl.so.2: OK, handle=55609a9c48d0
libmklml_intel.so: OK, handle=55609a9c4180
libonnxruntime.so.1.11.1: OK, handle=55609a9c9000
libpaddle2onnx.so.1.0.0rc2: OK, handle=55609a9cebe0'

### Steps to reproduce the bug

Inner Exception:
DllNotFoundException: Unable to load shared library 'paddle_inference_c' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux-x64/native/paddle_inference_c.so: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux/native/paddle_inference_c.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/paddle_inference_c.so: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/paddle_inference_c.so: cannot open shared object file: No such file or directory
libphi.so: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux/native/libpaddle_inference_c.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/libpaddle_inference_c.so: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/libpaddle_inference_c.so: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux-x64/native/paddle_inference_c: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux/native/paddle_inference_c: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/paddle_inference_c: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/paddle_inference_c: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux-x64/native/libpaddle_inference_c: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/runtimes/linux/native/libpaddle_inference_c: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8/libpaddle_inference_c: cannot open shared object file: No such file or directory
/mnt/d/Project/DemoConsoleApp/bin/Debug/net8.0/libpaddle_inference_c: cannot open shared object file: No such file or directory

I cannot find paddle_inference_c.so in native folder.
![Screenshot 2024-09-28 011220](https://github.com/user-attachments/assets/9ef93a10-433a-49a3-84c5-aaadb7dfc448)

### Release version

Sdcb.PaddleInference.runtime.linux64.mkl.gcc82 v2.6.0-preview.1

### IDE

Visual Studio 2022

### OS version

Windows 11 64bit

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp/issues/99#issuecomment-2184957707

**Comment by hodachuy** [comment]
Thank you, I was able to run it.
