### ISSUE TITLE
大佬能多集成几个paddlehub的东西么

### ISSUE THREAD

**Issue by bbhxwl** [sdcb/PaddleSharp#12]
人脸和人体关键点检测，做个火柴人的那种。
类似这种。
https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.2/modules/README_ch.md

**Comment by sdcb** [comment]
关键点检测本质是PaddleDetection，我集成到了一半，本质不难，但我这边没有需求，只是玩玩……

**Comment by bbhxwl** [comment]
> 关键点检测本质是PaddleDetection，我集成到了一半，本质不难，但我这边没有需求，只是玩玩……

好吧，学C#的搞ai，挺难
