### ISSUE TITLE
关于all.Run(img).Regions.Rect.Size

### ISSUE THREAD

**Issue by interiv** [sdcb/PaddleSharp#13]
var v = all.Run(img);

 foreach (var item in v.Regions)
            {
              
item 里面的 
item.Rect.Size.Height
item.Rect.Size.Width
这两个,你是弄反了吧?
看一下代码.
            }

**Comment by interiv** [comment]
![abc](https://user-images.githubusercontent.com/16269631/169473828-02c9965e-e3dd-4d5a-807d-f151442a641d.png)

你试试这张图,他会 纵横交错的识别位置.

**Comment by interiv** [comment]
![abcd](https://user-images.githubusercontent.com/16269631/169476421-3b5ab4c2-c7f7-4480-b4e3-8d20e9c2d59c.png)

**Comment by interiv** [comment]
用的是 从vs nuget上下载的 paddleocr, 是ppocr-v2.
版本是  2.2.2
比这里开源的版本号还要大.

观察过代码,代码却不一样.
是不是第三方放到的nuget上的?

**Comment by sdcb** [comment]
上你的代码吧，你的情况跟这些原因都没有关系，因为nuget永远是真实的。
另外说到第“三”方，我的代码其实都属于第“三”方，因为我不能代表百度。

**Comment by interiv** [comment]
已解决,总结一下
绘制方框的时候
我用的是

 var r = new Rect(
                    Convert.ToInt32(item.Rect.Center.X - item.Rect.Size.Height / 2),
                 Convert.ToInt32(item.Rect.Center.Y - item.Rect.Size.Width / 2),
                 Convert.ToInt32(item.Rect.Size.Width),
                Convert.ToInt32(item.Rect.Size.Height));



                Cv2.Rectangle(img, r, new Scalar(0, 0, 255),4);
                
如上代码,先自制方框,然后画出.因为有角度问题.所以,方框会发生旋转.

经过群内请教,思考可以如下
后来
                var r2 = item.Rect.BoundingRect();
                Cv2.Rectangle(img, r2, new Scalar(0, 255, 0), 2);
可以绘制外接矩形.但是 如果  item 的旋转角度 不是90的倍数,则外接矩形,与 此图形,(就是指矩形)不一致.

那么,可以用群内大佬给的代码

 PaddleOcrResult v = all.Run(img);
            var p = v.Regions.Select(item => item.Rect.Points().Select(x => (OpenCvSharp.Point)x));
         img.DrawContours(p,-1, new Scalar(255,0,  0),1);

通过绘制边缘的方式,来绘制.

我思路是绘制矩形,他思路是绘制边缘.
边缘数据不用考虑任何矩形和旋转的事儿.也不用考虑图形是什么样子.

从一开始,想框选文字的时候,就限制了,我的方向. 框选.
