### ISSUE TITLE
Unable to load DLL 'paddle_inference_c' or one of its dependencies

### ISSUE THREAD

**Issue by journey191** [sdcb/PaddleSharp#15]
I had installed the [latest Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe),but the exception still.
![image](https://user-images.githubusercontent.com/11626700/171575513-ac0e4347-91cb-430d-a87f-d781eb6729b9.png)

**Comment by sdcb** [comment]
can you try have some troubleshooting using Dependency Walker? https://github.com/lucasg/Dependencies

**Comment by journey191** [comment]
> 

现在按文档引用各个包之后正常了，可能之前是工程缺少一些包的引用？（我不知道之前具体是缺少什么包，因为之前的测试项目已经被删掉了）

**Comment by journey191** [comment]
现在按文档引用各个包之后正常了，可能之前是工程缺少一些包的引用？（我不知道之前具体是缺少什么包，因为之前的测试项目已经被删掉了）
