### ISSUE TITLE
请问如何修改配置？

### ISSUE THREAD

**Issue by Camphora7** [sdcb/PaddleSharp#24]
![image](https://user-images.githubusercontent.com/108849683/192679622-fe7c4757-78b8-4c96-9fb6-c19625ec8100.png)
目前只知道这几条配置的修改，但是其他如下图的配置没有找到在哪里可以设置，请问如何修改下述配置呢？
![image](https://user-images.githubusercontent.com/108849683/192679792-9caee37c-ddd4-4f3c-b4d5-1a189a83760a.png)

**Comment by sdcb** [comment]
all.Detector.***
all.Recognizer.***
all.Classifier.***
