### ISSUE TITLE
NuGet package with binary deps for linux x64

### ISSUE THREAD

**Issue by lejsekt** [sdcb/PaddleSharp#25]
Hey,
I haven't found a NuGet package containing the binary dependencies for linux x64 platform. I've created one (based on the provided Dockerfile) for internal use as the provided docker images are sufficient for deployment, but not development scenarios. I'm now dockerizing the build of the package. Would you be interested in a PR? What are you thoughts on this?

**Comment by sdcb** [comment]
Hi 
I tried but it seems very hard to make it working on a raw linux environment without further package-installation.
I'm happy to see you can make it work and I'm open to any PR, but I have to confirm how you made it and is it really works :)

**Comment by lejsekt** [comment]
It's working for me in Ubuntu Focal and Ubuntu Jammy docker container. It's just taking the binaries used to produce the docker images to produce a NuGet package instead.

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal as builder

WORKDIR /

RUN apt-get update && apt-get -y install --no-install-recommends \
    wget \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q https://paddle-inference-lib.bj.bcebos.com/2.3.2/cxx_c/Linux/CPU/gcc8.2_avx_mkl/paddle_inference_c.tgz

RUN tar -xzf /paddle_inference_c.tgz && \
    mkdir -p /build/lib && \
    find /paddle_inference_c -mindepth 2 -name *.so* -print0 | xargs -0 -I {} mv {} /build/lib && \
    ls /usr/lib/*.so* && \
    rm -rf /paddle_inference_c && \
    rm paddle_inference_c.tgz

WORKDIR /build

COPY PaddleInference.runtime.linux-x64.csproj .

RUN dotnet pack -c Release -o package

FROM scratch

COPY --from=builder /build/package .
```

PaddleInference.runtime.linux-x64.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <VersionPrefix>0.1.0</VersionPrefix>
        <VersionSuffix>SNAPSHOT</VersionSuffix>
        <TargetFramework>netstandard2.0</TargetFramework>       
        <Description>Linux native dependecies for Paddle</Description>        
        <NoBuild>true</NoBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="lib/**" PackagePath="runtimes/linux-x64/native" Visible="false" />
    </ItemGroup>
</Project>
```

And then build it with: `docker buildx build . -o export`

And when one uses the package, it's necessary to add runtimes/linux-x64/native dir to LD_LIBRARY_PATH.

**Comment by sdcb** [comment]
Actually in my build-native.linq script it can generate the linux nuget package automatically.
I believe this only contains paddle inference reference, however it is very likely not working when installed in a raw linux machine without install other dependencies(likely specific version of GCC etc.), still need couples of debugging with `ldd`

**Comment by lejsekt** [comment]
In my opinion, it's not necessary to support a raw linux machine with the nuget package. But it should enable developers on linux to use the library more easily. Otherwise, it's necessary to somehow setup a docker environment for development.

If there's a script to produce the package already, that's great. Do you think you could publish that package as part of the release procedure? In a similar manner as the windows one.

**Comment by sdcb** [comment]
Yes I can publish the Linux nuget package, however I believe a lots of client will be very hard to understand a nuget package isn't enough to run LOL, they will very likely choose docker to run in Linux.
However if I not publish, they will surely ask LOL~

**Comment by sdcb** [comment]
@lejsekt please checkout the nuget package and have a test, please tell me if there is any question:
https://www.nuget.org/packages/Sdcb.PaddleInference.runtime.linux64.mkl.gcc82/2.3.2-preview.1

Please note that linux is linking some dynamic libraries with symlinks, however it's does not supported in Linux, so I made a few copies(which isn't very efficient)

**Comment by lejsekt** [comment]
Thanks, I'll give it a try.

**Comment by lejsekt** [comment]
Works as expected, thanks. Looking forward to a release version of the package.

**Comment by sdcb** [comment]
> Works as expected, thanks. Looking forward to a release version of the package.

I think I shouldn't make a release version because it seems not make sense by hard copy these linked .so files.
