### ISSUE TITLE
 Can't await all.run() when using GPU

### ISSUE THREAD

**Issue by DancingDolphins** [sdcb/PaddleSharp#26]
when using PaddleConfig.Defaults.UseGpu = True
  await    result = all.Run(src2)
throw  "System.AccessViolationException"
but using  PaddleConfig.Defaults.UseGpu = False
  await    result = all.Run(src2) seen OK to me

![Snipaste_2022-11-09_21-25-05](https://user-images.githubusercontent.com/30310389/200841923-1302be5d-2f1f-4851-9f1d-f9e6120fa9c6.png)

反正各种不能await。只要一套在await里必报错
一会试试放在多线程里是否可以。
已经在难受了。。

当然。如果没有await 。use GPU是OK的。但是总不能让用户界面假死很苦手。一张图片500ms的延迟不能忍受。

**Comment by sdcb** [comment]
Yes I can confirm, you cannot use multi-thread when GPU is enabled, it's a issue from upstream paddle_inference: 
https://github.com/PaddlePaddle/Paddle/issues/47081
https://github.com/PaddlePaddle/Paddle/issues/45437
https://github.com/PaddlePaddle/Paddle/issues/28044

**Comment by sdcb** [comment]
You can use a Queue+Single threaded recognize, so that it won't block UI thread while gain performance.
