### ISSUE TITLE
How to compress the size of dependency?

### ISSUE THREAD

**Issue by chocolatedesue** [sdcb/PaddleSharp#29]
感谢dalao的工作！

似乎您的项目将官方提供的模型全部打包成了dll

能否手动引用模型路径, 调用FileRecognizationModel载入模型, 然后删掉一些dll?

**Comment by sdcb** [comment]
当然可以，请参考下面这两段代码：
https://github.com/sdcb/PaddleSharp/blob/e457c9f104d7f878c87145c42ed6faadce66dbda/src/Sdcb.PaddleOCR/Models/FullOcrModel.cs#L7
https://github.com/sdcb/PaddleSharp/blob/e457c9f104d7f878c87145c42ed6faadce66dbda/src/Sdcb.PaddleOCR/Models/ClassificationModel.cs#L13
