### ISSUE TITLE
请问为什么我在运行目录下面没有找到模型但是能正常预测？

### ISSUE THREAD

**Issue by futureflsl** [sdcb/PaddleSharp#32]
请问为什么我在运行目录下面没有找到模型但是能正常预测，没有看到paddle推理模型，是序列化在DLL文件里面了吗

**Comment by sdcb** [comment]
你没猜错，放在本地文件中其实对许多环境都是不友好的，现在的机制是以嵌入资源的形式放到了Models.LocalV3里面，当然你也可以使用本地文件中的模型，不冲突。

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp/blob/7df28d4ec1e582ac5eae258dad72d605e23dcf04/src/Sdcb.PaddleOCR.Models.Online/Settings.cs#L8
https://github.com/sdcb/PaddleSharp/blob/7df28d4ec1e582ac5eae258dad72d605e23dcf04/src/Sdcb.PaddleOCR.Models.Online/OnlineDetectionModel.cs#L12
https://github.com/sdcb/PaddleSharp/blob/7df28d4ec1e582ac5eae258dad72d605e23dcf04/src/Sdcb.PaddleOCR.Models.Online/Details/Utils.cs#L52

https://jimrich.sk/environment-specialfolder-on-windows-linux-and-os-x/
> ENM: System.Environment.SpecialFolder.ApplicationData
> WIN: C:\Users\jariq\AppData\Roaming
> LIN: /home/jariq/.config
> OSX: /Users/jariq/.config
