### ISSUE TITLE
实测比之前老版本识别率明显高出不少，相比老版本新的内核有啥变化？

### ISSUE THREAD

**Issue by wangning08115** [sdcb/PaddleSharp#36]
实测比之前老版本识别率明显高出不少，相比老版本新的内核有啥变化？

1.之前老版本总是识别出重复数字，  比如 123456， 总是出现  1[22]3456  出现重复的数字
2.新版本效果明显，不会识别重复

下图在老版本内核上 总是出现重复数字，  新版本 完美。
![image](https://user-images.githubusercontent.com/3455705/226773779-12c6081a-ecb0-435c-be65-440fbf190a5c.png)

**Comment by sdcb** [comment]
取决于你的老版本有多老，这个精度方面有如下升级：
* 最初版本，只支持V2模型，精度稍低
* 2.5版本，支持V3模型，但高度没有设置为48（而是32），导致精度仍然稍低
* 后续某个版本（可能是2.6？），修复了这个bug，高度正确地设置为了48，精度变高了。
