### ISSUE TITLE
找不到字段:“Sdcb.PaddleInference.PaddleConfig.Defaults”

### ISSUE THREAD

**Issue by wangning08115** [sdcb/PaddleSharp#38]
无法调用配置项：

`PaddleConfig.Defaults.EnableGLog = EnableGLog;
            PaddleConfig.Defaults.UseMkldnn = UseMkldnn;
            PaddleConfig.Defaults.MkldnnCacheCapacity = MkldnnCacheCapacity;`

只要调用那么这个函数据报错， 但是 后续的 OCR功能正常；

**Comment by wangning08115** [comment]
实测发现  Sdcb.PaddleInference 最新版本有bug， 2.3.2就不会报上边的错误了。 好神奇啊。

![image](https://user-images.githubusercontent.com/3455705/227697501-eb8344b3-40e5-41f0-b708-ad212c234102.png)

**Comment by wangning08115** [comment]
@sdcb 大佬 看样子是 nuget的 dll 版本对不上号啊。

**Comment by sdcb** [comment]
上面那些是最新版我删掉了，具体可以看这个页面：https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#how-to-migrate-previous-old-version-to-latest-2601

**Comment by wangning08115** [comment]
好的 ，感谢大佬
