### ISSUE TITLE
 One or more errors occurred. (External component has thrown an exception.)

### ISSUE THREAD

**Issue by huangye123** [sdcb/PaddleSharp#39]
1、测试验证环境
1.1、webapi服务，同时整合paddleocr和PaddleDetection，通过单例化模式在首次请求时会实例唯一对象。
1.2、CUDA 11.7 CUDNN 8.4 TensorRt 8.4 使用GPU模式推理
1.3、Windows11 操作系统

2、使用最新队列，消息者1，消息队列为32

3、运行过程报异常
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

【问题】
1、使用队列模式时，控制台没有输出日志
2、如何在调用时出现异常，能否在日志中记录底层的原因。

**Comment by sdcb** [comment]
如果使用QueuedPaddleOcrAll估计在GPU这边没问题，但如果使用PaddleDetection，取决于你的代码是怎么写的，有可能有问题

我测试发现PaddleInference创建predictor的线程和运行predictor的线程不一致就会crash，QueuedPaddleOcrAll做了特殊处理，如果你使用Queued这个类，就不会有问题。

**Comment by huangye123** [comment]
> 如果使用QueuedPaddleOcrAll估计在GPU这边没问题，但如果使用PaddleDetection，取决于你的代码是怎么写的，有可能有问题
> 
> 我测试发现PaddleInference创建predictor的线程和运行predictor的线程不一致就会crash，QueuedPaddleOcrAll做了特殊处理，如果你使用Queued这个类，就不会有问题。

使用Queued，消费者调整为1，运行了几天就正常了。非常感谢！
