### ISSUE TITLE
该库能否在并发环境使用

### ISSUE THREAD

**Issue by 2738644273** [sdcb/PaddleSharp#40]
该库能否在并发环境使用，我应该使用单例模式吗?

**Comment by sdcb** [comment]
请参考：https://github.com/sdcb/PaddleSharp/blob/master/docs/ocr.md#how-to-integrate-sdcbpaddleocr-to-aspnet-core
并传入consumerCount: 1
完整示例代码：https://github.com/sdcb/paddlesharp-ocr-aspnetcore-demo
这样就可以自动单例模式
