### ISSUE TITLE
显示在浏览器，网址匹配不区分大小写

### ISSUE THREAD

**Issue by cuiliang** [sdcb/PaddleSharp#43]
![image](https://user-images.githubusercontent.com/1972649/233772344-a2f2c645-5ba9-48c3-89a3-bcee95198b9a.png)

**Comment by n0099** [comment]
uri/url的scheme和domain部分的确不区分大小写，这是比uri更老的dns当年设计使然，但path部分是区分的
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier
```
 scheme:[//host[:port]][/]path[?query][#fragment]
 \____________________/\________________________/
        Location                 Data
```
https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive
https://www.searchenginejournal.com/google-urls-are-case-sensitive/421264/

**Comment by cuiliang** [comment]
抱歉，贴错地方了，请大佬删掉吧😂
