### ISSUE TITLE
 “Sdcb.PaddleInference.PaddleConfig”的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by yhl666mail** [sdcb/PaddleSharp#50]
报错代码：
FullOcrModel model = LocalFullModels.ChineseV3;
Action<PaddleConfig> action = PaddleDevice.Mkldnn(cpuMathThreadCount: 1);
using (PaddleOcrAll all = new PaddleOcrAll(model, action)   

报错信息：
在 Sdcb.PaddleInference.PaddleConfig.FromMemoryModel(Byte[] programBuffer, Byte[] paramsBuffer)
   在 Sdcb.PaddleOCR.Models.LocalV3.Details.Utils.LoadLocalModel(String key)
   在 Sdcb.PaddleOCR.Models.LocalV3.LocalTableRecognitionModel.CreateConfig()
   在 Sdcb.PaddleOCR.PaddleOcrTableRecognizer..ctor(TableRecognitionModel model, Action`1 configure)
 “Sdcb.PaddleInference.PaddleConfig”的类型初始值设定项引发异常。

我做的word vsto插件在 自己电脑word里面运行正常在wps里面运行报错。在同事电脑word wps均报错

**Comment by yhl666mail** [comment]
我做的word vsto插件在 自己电脑word里面运行正常在wps里面运行报错。在同时电脑word wps均报错

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp/blob/5e2588b57c2c44e3f31acc47d54360c5f1e0b90e/src/Sdcb.PaddleInference/PaddleConfig.cs#L66
https://github.com/sdcb/PaddleSharp/blob/5e2588b57c2c44e3f31acc47d54360c5f1e0b90e/src/Sdcb.PaddleInference/PaddleConfig.cs#LL20C35-L20C35
https://github.com/sdcb/PaddleSharp/blob/5e2588b57c2c44e3f31acc47d54360c5f1e0b90e/src/Sdcb.PaddleInference/Native/PaddleNative.g.cs#L12


https://learn.microsoft.com/en-us/dotnet/api/system.typeinitializationexception
请把innerexception发上来

**Comment by yhl666mail** [comment]
ex.InnerException.StackTrace: Sdcb.PaddleInference.PaddleConfig..cctor()

ex.InnerException.Message: Paddle Inference does not support 32bit platform.

电脑系统是64位

**Comment by n0099** [comment]
但您测试的word/wps程序应该是32而非64位构建，而paddleinfer也没有32位构建，所以您重装word/wps换64位吧

**Comment by yhl666mail** [comment]
找到问题了谢谢
