### ISSUE TITLE
建议发布nuget包时带上`.snupkg`符号

### ISSUE THREAD

**Issue by n0099** [sdcb/PaddleSharp#51]
https://nuget.info/packages/Sdcb.PaddleInference/2.4.1.2
![image](https://github.com/sdcb/PaddleSharp/assets/13030387/cd5c726f-bcf3-48b5-b6c4-5d7825961b06)

https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by sdcb** [comment]
好主意，我正准备带上

**Comment by n0099** [comment]
您需要这种 https://nuget.info/packages/Npgsql.EntityFrameworkCore.PostgreSQL/7.0.4
![image](https://github.com/sdcb/PaddleSharp/assets/13030387/ed41a01c-0d80-49dd-ae13-6416da714cce)
这样才能在vs+resharper环境中直接ctrl+click下载github源码文件并查看正确位置的源码
现在没带resharper只能即时反编译然后展示一大坨超长行冗余写法的IL转c#

**Comment by sdcb** [comment]
理解理解，我也有这个烦恼，正在想办法搞个大的提交

**Comment by sdcb** [comment]
Please refer to: https://github.com/sdcb/PaddleSharp/releases/tag/2.4.1.3
Added all packages symbol file and detailed xml comments.

**Comment by n0099** [comment]
![image](https://github.com/sdcb/PaddleSharp/assets/13030387/ead67fe5-9424-4b83-97ea-2ecaaad21f34)
https://nuget.info/packages/Sdcb.PaddleInference/2.4.1.3
