### ISSUE TITLE
一些图片识别的文字顺序错乱

### ISSUE THREAD

**Issue by a442509097** [sdcb/PaddleSharp#55]
这个是一个模拟器游戏里的图片, 句子本应该是

"Reality faded away as time stood still."

被识别成了

"stood still. time faded Reality as away"

已更新到[2.4.1.3](https://github.com/sdcb/PaddleSharp/releases/tag/2.4.1.3)版本
大部分正常识别, 少数会出现这样的情况.
![捕获](https://github.com/sdcb/PaddleSharp/assets/17733616/63da2195-719c-49e8-8a81-f69497968964)

对了我是区域截图识别, 所以不包含左上角那些信息, 实际图片如下
![temp](https://github.com/sdcb/PaddleSharp/assets/17733616/e3e9cf36-672b-4afc-ac79-0393d8ab7979)

**Comment by sdcb** [comment]
这个是不保证顺序的，但你可以按照自己的需求进行排序，现在默认是先按包围矩形的y坐标排序，再按包围矩形的x坐标排序。

**Comment by n0099** [comment]
可以参考我的文本框排序方式 https://github.com/n0099/open-tbm/blob/dcf4423d8d9621b1335955f42aafa879d2eb3bb8/c%23/imagePipeline/src/Ocr/JoinedRecognizer.cs#L55

**Comment by n0099** [comment]
> 让我理解一下，你的做法实际上是将图片grid化，比如原先高度1000px的图片，正规化到20个grid单位，这样不容易出现识别后微小的高度不一致时导致排序错误的问题，对吧？但问题可能仍然会存在，在一些场景中可能碰巧正好正规化到不同的grid中了

差不多，但实际上`GridSizeToMergeBoxesIntoSingleLine`的单位是px，因为源自opencv mat大小的文本框大小也是px
而其默认值`10px`意味着当两个文本框的`y`整数除法`10px`后如果相同就视作在同一行中
这显然不适用于竖排文本（文言文，日文），对其需要把判断`y`改成`x`
