### ISSUE TITLE
文本检测问题：用PaddleOcr训练的检测模型，在PaddleSharp中效果不好

### ISSUE THREAD

**Issue by eyesyang** [sdcb/PaddleSharp#56]
大佬，帮忙看看什么问题？
第一张是在paddlesharp运行的结果
paddlesharp没有做任何修改
第二张是在paddleocr运行的结果
paddleocr中有修改source code，注释了一下两行code：
# 'limit_side_len': args.det_limit_side_len,
# 'limit_type': args.det_limit_type,
![output](https://github.com/sdcb/PaddleSharp/assets/6211068/d9d2a714-08ad-4f15-bc84-334fa4d8416b)
![0_0](https://github.com/sdcb/PaddleSharp/assets/6211068/6255a56e-ec33-4804-9d6a-6fdb34015d25)

**Comment by sdcb** [comment]
需要更多信息。

**Comment by n0099** [comment]
#57
