### ISSUE TITLE
Exception in PaddleOcrAll.Run with custom trained ocr recognization model

### ISSUE THREAD

**Issue by tsebring** [sdcb/PaddleSharp#57]
Hello,

I have a custom trained ocr recognition model that has been working well in my application in Python PaddleOCR. I wanted to see if I could get the same application running in C# with this .NET wrapper, but there is something wrong.

When I plug in my custom model the call to PaddleOcrAll.Run throws an exception ("External component has thrown an exception.") for some images but not all.

Any idea what is going on here?

I have attached a solution reproducing the issue based on the ocr sample code and two example images from this repo.
![image](https://github.com/sdcb/PaddleSharp/assets/408350/0426b799-dfa4-4fae-b127-13461c629b53)

[PaddleSharp_Example.zip](https://github.com/sdcb/PaddleSharp/files/11923441/PaddleSharp_Example.zip)

**Comment by sdcb** [comment]
Strange, I just tried switch `PaddleDevice.Openblas()`, it works, maybe it's a bug in `mkldnn`?

**Comment by tsebring** [comment]
You are absolutely right! I tried switching from Python PaddleOCR to mkldnn, and it worked, but the recognized text becomes a jumbled mess. When using `paddlepaddle-gpu`, the same model works fine again. Similarly, the example solution in PaddleSharp works with `PaddleDevice.Gpu()`.

**Comment by sdcb** [comment]
ok, considering this is a issue from upstream, then I close this ticket.
