### ISSUE TITLE
使用Window GPU， ocr后显存不释放导致错误？

### ISSUE THREAD

**Issue by DimWalker** [sdcb/PaddleSharp#6]
代码大致如下图，一个静态实例，执行两次Run后，会报
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”
或偶尔报 CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR.
使用CPU时没有此问题（单线程），请问该如何正确使用GPU进行OCR？

![image](https://user-images.githubusercontent.com/8163821/165343989-619d50d3-ac6a-45f8-9368-6ebdcaafa4b2.png)

**Comment by DimWalker** [comment]
问题补充：
上面是在MVC项目里执行。
在Console里测试，for循环多次执行不会报错，但是Console结束时报错CUDA error(4), driver shutting down.

**Comment by sdcb** [comment]
会不会是因为调用OcrAll是不同的线程导致的？

**Comment by DingShawn** [comment]
我也遇到这个问题了，读取模型和预测不在同一个线程GPU预测会报错，Cpu没问题（也有极小概率出现问题），请问有没有解决的思路能指导一下
![image](https://user-images.githubusercontent.com/37792269/169012814-3e75d3d2-3401-42a5-8562-46db8fcde4a9.png)

**Comment by DingShawn** [comment]
结束调试后会报CUDNN错误，at ..\paddle/fluid/platform/device_context.h:429
![image](https://user-images.githubusercontent.com/37792269/169013463-75de7b40-085c-4055-ac68-153ed114412c.png)

**Comment by DimWalker** [comment]
> 结束调试后会报CUDNN错误，at ..\paddle/fluid/platform/device_context.h:429 ![image](https://user-images.githubusercontent.com/37792269/169013463-75de7b40-085c-4055-ac68-153ed114412c.png)

两个问题，不同线程和cudnn错误的问题：

1、线程的话，自己新建一个线程实例，执行方法内先初始化Ocr Gpu实例，然后死循环轮询。优雅点可以找找线程池的源代码，模仿它是怎么实现的。
不爆显存的情况下可以多个实例共用同一块GPU，但效果提升并不明显，不推荐。

2、cudnn错误，没解决，但是不太严重。做成web api的话，这个不影响。这个有可能是paddle的问题，参考https://blog.csdn.net/u011622208/article/details/109186153
