### ISSUE TITLE
是否考虑支持ARM64下运行

### ISSUE THREAD

**Issue by CrazyJson** [sdcb/PaddleSharp#60]
基于sdflysha/dotnet6-paddle这个镜像可构建x86下的运行镜像，是否考虑制作arm64的基础镜像

**Comment by n0099** [comment]
paddleinfer不支持arm吧

**Comment by CrazyJson** [comment]
百度了下，需要自行编译paddleinfer

**Comment by whSwitching** [comment]
大佬不如考虑下搞个 PaddleLiteSharp  甚至做成MAUI的包

**Comment by sdcb** [comment]
你好，ARM64推理我已经在OpenVINO.NET中实现了，请享用：https://github.com/sdcb/OpenVINO.NET
