### ISSUE TITLE
Sdcb.PaddleOCR.Models.LocalV3.dll这个组件到达了152M

### ISSUE THREAD

**Issue by Farb** [sdcb/PaddleSharp#62]
Sdcb.PaddleOCR.Models.LocalV3.dll这个组件到达了152M，有没有小一点的，或者再压缩下？我看PaddleOCR给的模型不都是很小嘛，就十几M。

**Comment by n0099** [comment]
这是把所有百度训练并公开下载的语言模型都缝合进去了的
您可以用在线即时下载的 https://www.nuget.org/packages/Sdcb.PaddleOCR.Models.Online/

**Comment by Farb** [comment]
建议将语言模型分开封装，用户需要什么语言安装什么语言即可。@sdcb

**Comment by n0099** [comment]
您提前下下来模型文件放到默认或修改后的全局变量`GlobalModelDirectory`里不就行了？
