### ISSUE TITLE
KIE example (SER, RE)

### ISSUE THREAD

**Issue by PaulKuzmin** [sdcb/PaddleSharp#64]
Hello

You've done a tremendous job. I actively use your development in my projects. Thank you very much.

Currently, I have a task of extracting structured data from documents (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/algorithm_kie_vi_layoutxlm_en.md). I've trained my own model and verified it using Python.

Now, I would like to use my model with PaddleSharp. Could you please advise me on how to do this? Please provide an example.

Thank you once again.

**Comment by sdcb** [comment]
Upstream code seems not provide C++ examples, I also don't get a chance to look at it, I suggest you follow the python code in PaddlePaddle/PaddleOCR repository.

**Comment by PaulKuzmin** [comment]
Thanks.
