### ISSUE TITLE
Feature request: Support for PaddleSpeech

### ISSUE THREAD

**Issue by JohnWhite8888** [sdcb/PaddleSharp#7]
Is there any plans to support PaddleSpeech ?
Any pointer or help how to start is appreciated, I might be able to help

**Comment by sdcb** [comment]
I'm looking for a C/C++ example of PaddleSpeech to make it happen.

**Comment by sdcb** [comment]
It seems there is no C/C++ sample of PaddleSpeech, I'll close this ticket unless you find it.
