### ISSUE TITLE
ONNX Optimizations

### ISSUE THREAD

**Issue by theonewolf** [sdcb/PaddleSharp#74]
@sdcb I saw in your code (and Paddle upstream) that we are applying ORT Optimization.

Is there any method of also applying further memory optimizations like this:

```C#
            SessionOptions so = new SessionOptions();

            // I assume this is already done by you + Paddle.
            so.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;

            // What about these two?  I've seen large memory savings with them.
            so.EnableCpuMemArena = false;
            so.EnableMemoryPattern = false;
```

**Comment by theonewolf** [comment]
Got it.  We can close this.  Just note that if you can get CpuMemArena turned off I saw significant memory savings with other DNNs on ONNX.

**Comment by sdcb** [comment]
Can you try with my other project: [openvino](https://github.com/sdcb/OpenVINO.NET) It also supports ONNX model inference but performs better than PaddleSharp.

**Comment by theonewolf** [comment]
@sdcb I am trying to do things with a budget of 300-400 MB RAM :-p I will see what I can do with openvino!

I will try OCR with openvino.  Thank you for the link!  Also for all the very excellent C# projects.
