### ISSUE TITLE
Question : PaddleClas integration

### ISSUE THREAD

**Issue by aboccag** [sdcb/PaddleSharp#77]
Hello,

I just would like to know if the library is compatible with PaddleSharp. For example using a ResNet50_vd model to classify images to classes.

Best regards

**Comment by sdcb** [comment]
Yes I tried it's compatible, all models that able to runs in paddle inference c api should compatible with paddlesharp.

**Comment by aboccag** [comment]
Thank you very much! Would it be possible to get just a quick simple code sample just to make sure i'm using it correctly ? 

Best regards!
