### ISSUE TITLE
支持ARM64吗

### ISSUE THREAD

**Issue by JaneConan** [sdcb/PaddleSharp#8]

**Comment by sdcb** [comment]
不支持，因为Paddle推理加不支持ARM64，必须要用PaddleLite，但PaddleLite不支持C API。
Not supported, since paddle-inference does not support ARM64, must using PaddleLite, however PaddleLite does not support C API.

**Comment by JaneConan** [comment]
必须要用PaddleLite？但不支持C API，那然后实现arm64的跨平台呢

**Comment by JaneConan** [comment]
> 不支持，因为Paddle推理加不支持ARM64，必须要用PaddleLite，但PaddleLite不支持C API。 Not supported, since paddle-inference does not support ARM64, must using PaddleLite, however PaddleLite does not support C API.

必须要用PaddleLite？但不支持C API，那如何实现arm64的跨平台呢

**Comment by sdcb** [comment]
要使用像 https://github.com/shimat/opencvsharp 的实现方式，使用C API封装一遍PaddleLite，然后再用C#来包装C API，这样就会麻烦得多，需要花费PaddleSharp好几倍的工作量。

**Comment by JaneConan** [comment]
> 要使用像 https://github.com/shimat/opencvsharp 的实现方式，使用C API封装一遍PaddleLite，然后再用C#来包装C API，这样就会麻烦得多，需要花费PaddleSharp好几倍的工作量。

多谢解答~ 您们有计划么，我们可以一起参与~
