### ISSUE TITLE
升级4.9.0后，报【找不到字段:"OpenCvShap.Size.Zero"】错误

### ISSUE THREAD

**Issue by letheliu** [sdcb/PaddleSharp#81]
如题

**Comment by n0099** [comment]
#78

**Comment by sdcb** [comment]
https://github.com/shimat/opencvsharp/issues/1640

**Comment by sdcb** [comment]
应该解决了，使用最新版即可。

**Comment by Jiangmitiaotiao** [comment]
Version 2.7.0.3 of Sdcb.PaddleOCR and version 4.10 of OpenCvSharp still throw an exception System.MissingFieldException: 'Cannot find field: OpenCvSharp.Size.Zero'.
