### ISSUE TITLE
有轻量级的部署方案吗

### ISSUE THREAD

**Issue by itachi1232gg** [sdcb/PaddleSharp#84]
你好，我按readme里的指引用nuget装了相关的依赖后，一个简单的console程序生成的release文件夹有600+M。 OCR只是我程序里很小的一个组件，文件大小比我整个项目编译后都大了。 请问有什么轻量级的部署方案吗？ 模型我只需要V4里的英语检测和识别模型，外加一个方向分类模型。
![image](https://github.com/sdcb/PaddleSharp/assets/8243929/74944fa0-25ea-4d1b-b772-6b42ef008aac)

**Comment by n0099** [comment]
您为什么要同时用v3和v4模型？还是缝合了所有可用语言模型文件的`Local`包`.dll`
换`Online` https://github.com/sdcb/PaddleSharp/issues/62#issuecomment-1655267863

**Comment by itachi1232gg** [comment]
我nuget装了model.local， 我试一下online， 谢谢。
