### ISSUE TITLE
Regarding the issue of OCR

### ISSUE THREAD

**Issue by lindadamama** [sdcb/PaddleSharp#94]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

 if I only want to call the REC model, how can I make the det and cls models not work?

### Describe the solution you'd like

Just using the functionality of the REC model

**Comment by sdcb** [comment]
just create this: https://github.com/sdcb/PaddleSharp/blob/f0cf603aea0a438d17f6b711785bf18d338ee536/src/Sdcb.PaddleOCR/PaddleOcrRecognizer.cs#L14

**Comment by lindadamama** [comment]
Thank you, I will give it a try

**Comment by lindadamama** [comment]
It worked perfectly. Thank you
